# Generated by Django 5.0 on 2023-12-12 01:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_product_last_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_have",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
